from typing import Protocol
from uuid import UUID

from employee_api.domain.entities import Employee, EmployeeSummary, User


class EmployeeRepository(Protocol):
    def summary(self) -> EmployeeSummary: ...
    def get(self, employee_id: UUID, *, for_update: bool = False) -> Employee | None: ...
    def list(
        self, offset: int, limit: int, name: str | None, dpi: str | None
    ) -> tuple[list[Employee], int]: ...
    def save(self, employee: Employee) -> Employee: ...
    def delete(self, employee_id: UUID) -> None: ...


class AuditRepository(Protocol):
    def record(
        self, actor_id: UUID, employee_id: UUID, action: str, changed_fields: list[str]
    ) -> None: ...


class UnitOfWork(Protocol):
    employees: EmployeeRepository
    audit: AuditRepository

    def __enter__(self) -> "UnitOfWork": ...
    def __exit__(self, exc_type, exc_value, traceback) -> None: ...
    def commit(self) -> None: ...


class UserRepository(Protocol):
    def by_username(self, username: str) -> User | None: ...
    def by_id(self, user_id: UUID) -> User | None: ...
