/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/health/live": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Live */
    get: operations["live_health_live_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/health/ready": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Ready */
    get: operations["ready_health_ready_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/token": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Login */
    post: operations["login_api_v1_auth_token_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Me */
    get: operations["me_api_v1_auth_me_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/employees": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Employees */
    get: operations["list_employees_api_v1_employees_get"];
    put?: never;
    /** Create Employee */
    post: operations["create_employee_api_v1_employees_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/employees/summary": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Employee Summary */
    get: operations["employee_summary_api_v1_employees_summary_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/employees/{employee_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Employee */
    get: operations["get_employee_api_v1_employees__employee_id__get"];
    /** Replace Employee */
    put: operations["replace_employee_api_v1_employees__employee_id__put"];
    post?: never;
    /** Delete Employee */
    delete: operations["delete_employee_api_v1_employees__employee_id__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/employees/{employee_id}/salary": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update Salary */
    patch: operations["update_salary_api_v1_employees__employee_id__salary_patch"];
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** AddressDTO */
    AddressDTO: {
      /** Line1 */
      line1: string;
      /** Municipality */
      municipality: string;
      /** Department */
      department: string;
      /**
       * Country
       * @default GT
       */
      country: string;
      /** Line2 */
      line2?: string | null;
      /** Postal Code */
      postal_code?: string | null;
    };
    /** Body_login_api_v1_auth_token_post */
    Body_login_api_v1_auth_token_post: {
      /** Grant Type */
      grant_type?: string | null;
      /** Username */
      username: string;
      /**
       * Password
       * Format: password
       */
      password: string;
      /**
       * Scope
       * @default
       */
      scope: string;
      /** Client Id */
      client_id?: string | null;
      /**
       * Client Secret
       * Format: password
       */
      client_secret?: string | null;
    };
    /** EmployeePage */
    EmployeePage: {
      /** Items */
      items: components["schemas"]["EmployeeRead"][];
      /** Total */
      total: number;
      /** Offset */
      offset: number;
      /** Limit */
      limit: number;
    };
    /** EmployeeRead */
    EmployeeRead: {
      /** First Names */
      first_names: string;
      /** Last Names */
      last_names: string;
      gender: components["schemas"]["Gender"];
      marital_status: components["schemas"]["MaritalStatus"];
      /**
       * Birth Date
       * Format: date
       */
      birth_date: string;
      /** Dpi */
      dpi: string;
      /** Nit */
      nit: string;
      /** Igss Number */
      igss_number?: string | null;
      /** Irtra Number */
      irtra_number?: string | null;
      /** Addresses */
      addresses: components["schemas"]["AddressDTO"][];
      salary: components["schemas"]["SalaryDTO-Output"];
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
      /** Age */
      readonly age: number;
    };
    /** EmployeeSummaryRead */
    EmployeeSummaryRead: {
      /** Total */
      total: number;
      /** Igss Count */
      igss_count: number;
      /** Irtra Count */
      irtra_count: number;
      /** Address Count */
      address_count: number;
      /** Genders */
      genders: components["schemas"]["GenderCountRead"][];
      /** Salaries */
      salaries: components["schemas"]["SalarySummaryRead"][];
    };
    /** EmployeeWrite */
    EmployeeWrite: {
      /** First Names */
      first_names: string;
      /** Last Names */
      last_names: string;
      gender: components["schemas"]["Gender"];
      marital_status: components["schemas"]["MaritalStatus"];
      /**
       * Birth Date
       * Format: date
       */
      birth_date: string;
      /** Dpi */
      dpi: string;
      /** Nit */
      nit: string;
      /** Igss Number */
      igss_number?: string | null;
      /** Irtra Number */
      irtra_number?: string | null;
      /** Addresses */
      addresses: components["schemas"]["AddressDTO"][];
      salary: components["schemas"]["SalaryDTO-Input"];
    };
    /**
     * Gender
     * @enum {string}
     */
    Gender: "FEMALE" | "MALE" | "OTHER" | "UNSPECIFIED";
    /** GenderCountRead */
    GenderCountRead: {
      gender: components["schemas"]["Gender"];
      /** Count */
      count: number;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /**
     * MaritalStatus
     * @enum {string}
     */
    MaritalStatus:
      "SINGLE" | "MARRIED" | "DIVORCED" | "WIDOWED" | "CIVIL_UNION";
    /**
     * PayFrequency
     * @enum {string}
     */
    PayFrequency: "MONTHLY" | "BIWEEKLY" | "WEEKLY";
    /**
     * Role
     * @enum {string}
     */
    Role: "HR_ADMIN" | "EMPLOYEE_VIEWER";
    /** SalaryDTO */
    "SalaryDTO-Input": {
      /** Base Amount */
      base_amount: number | string;
      /**
       * Bonus Amount
       * @default 0.00
       */
      bonus_amount: number | string;
      /**
       * Currency
       * @default GTQ
       */
      currency: string;
      /** @default MONTHLY */
      pay_frequency: components["schemas"]["PayFrequency"];
    };
    /** SalaryDTO */
    "SalaryDTO-Output": {
      /** Base Amount */
      base_amount: string;
      /**
       * Bonus Amount
       * @default 0.00
       */
      bonus_amount: string;
      /**
       * Currency
       * @default GTQ
       */
      currency: string;
      /** @default MONTHLY */
      pay_frequency: components["schemas"]["PayFrequency"];
    };
    /** SalaryPatch */
    SalaryPatch: {
      /** Base Amount */
      base_amount?: number | string | null;
      /** Bonus Amount */
      bonus_amount?: number | string | null;
      /** Currency */
      currency?: string | null;
      pay_frequency?: components["schemas"]["PayFrequency"] | null;
    };
    /** SalarySummaryRead */
    SalarySummaryRead: {
      /** Currency */
      currency: string;
      pay_frequency: components["schemas"]["PayFrequency"];
      /** Employee Count */
      employee_count: number;
      /** Base Total */
      base_total: string;
      /** Bonus Total */
      bonus_total: string;
    };
    /** TokenResponse */
    TokenResponse: {
      /** Access Token */
      access_token: string;
      /**
       * Token Type
       * @default bearer
       */
      token_type: string;
    };
    /** UserRead */
    UserRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Username */
      username: string;
      role: components["schemas"]["Role"];
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  live_health_live_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  ready_health_ready_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  login_api_v1_auth_token_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/x-www-form-urlencoded": components["schemas"]["Body_login_api_v1_auth_token_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TokenResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  me_api_v1_auth_me_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserRead"];
        };
      };
    };
  };
  list_employees_api_v1_employees_get: {
    parameters: {
      query?: {
        offset?: number;
        limit?: number;
        name?: string | null;
        dpi?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EmployeePage"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_employee_api_v1_employees_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EmployeeWrite"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EmployeeRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  employee_summary_api_v1_employees_summary_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EmployeeSummaryRead"];
        };
      };
    };
  };
  get_employee_api_v1_employees__employee_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        employee_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EmployeeRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  replace_employee_api_v1_employees__employee_id__put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        employee_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EmployeeWrite"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EmployeeRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_employee_api_v1_employees__employee_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        employee_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_salary_api_v1_employees__employee_id__salary_patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        employee_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SalaryPatch"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EmployeeRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
