"""initial employee management schema

Revision: 0001
"""

import sqlalchemy as sa
from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "employees",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("first_names", sa.String(length=100), nullable=False),
        sa.Column("last_names", sa.String(length=100), nullable=False),
        sa.Column("gender", sa.String(length=20), nullable=False),
        sa.Column("marital_status", sa.String(length=20), nullable=False),
        sa.Column("birth_date", sa.Date(), nullable=False),
        sa.Column("dpi", sa.String(length=13), nullable=False),
        sa.Column("nit", sa.String(length=20), nullable=False),
        sa.Column("igss_number", sa.String(length=30), nullable=True),
        sa.Column("irtra_number", sa.String(length=30), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("gender IN ('FEMALE','MALE','OTHER','UNSPECIFIED')", name="ck_gender"),
        sa.CheckConstraint(
            "marital_status IN ('SINGLE','MARRIED','DIVORCED','WIDOWED','CIVIL_UNION')",
            name="ck_marital_status",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dpi"),
        sa.UniqueConstraint("nit"),
    )
    op.create_index(op.f("ix_employees_first_names"), "employees", ["first_names"], unique=False)
    op.create_index(op.f("ix_employees_last_names"), "employees", ["last_names"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=30), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.CheckConstraint("role IN ('HR_ADMIN','EMPLOYEE_VIEWER')", name="ck_user_role"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "addresses",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("employee_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("line1", sa.String(length=250), nullable=False),
        sa.Column("line2", sa.String(length=250), nullable=True),
        sa.Column("municipality", sa.String(length=100), nullable=False),
        sa.Column("department", sa.String(length=100), nullable=False),
        sa.Column("country", sa.String(length=2), nullable=False),
        sa.Column("postal_code", sa.String(length=12), nullable=True),
        sa.ForeignKeyConstraint(["employee_id"], ["employees.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_addresses_employee_id"), "addresses", ["employee_id"], unique=False)
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=False),
        sa.Column("employee_id", sa.Uuid(), nullable=False),
        sa.Column("action", sa.String(length=10), nullable=False),
        sa.Column("changed_fields", sa.JSON(), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_logs_actor_id"), "audit_logs", ["actor_id"], unique=False)
    op.create_index(op.f("ix_audit_logs_employee_id"), "audit_logs", ["employee_id"], unique=False)
    op.create_table(
        "salary_information",
        sa.Column("employee_id", sa.Uuid(), nullable=False),
        sa.Column("base_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("bonus_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("pay_frequency", sa.String(length=20), nullable=False),
        sa.CheckConstraint(
            "pay_frequency IN ('MONTHLY','BIWEEKLY','WEEKLY')", name="ck_pay_frequency"
        ),
        sa.CheckConstraint("base_amount >= 0 AND bonus_amount >= 0", name="ck_salary_nonnegative"),
        sa.ForeignKeyConstraint(["employee_id"], ["employees.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("employee_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("salary_information")
    op.drop_index(op.f("ix_audit_logs_employee_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_actor_id"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_addresses_employee_id"), table_name="addresses")
    op.drop_table("addresses")
    op.drop_table("users")
    op.drop_index(op.f("ix_employees_last_names"), table_name="employees")
    op.drop_index(op.f("ix_employees_first_names"), table_name="employees")
    op.drop_table("employees")
    # ### end Alembic commands ###
